workflows:
  native-android:
    name: Native Android
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      android_signing:
        - bridesandgrooms_keystore
      groups:
        - google_play
        - magic_values
      vars:
        PACKAGE_NAME: "com.bridesandgrooms.event"
    scripts:
      - name: Set Android SDK location
        script: | 
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"
          
      - name: Grant Execute Permission to gradlew
        script: |
          chmod +x gradlew
          
      - name: Build Android release
        script: | 
          LATEST_GOOGLE_PLAY_BUILD_NUMBER=$(google-play get-latest-build-number --package-name "$PACKAGE_NAME")
          if [ -z $LATEST_GOOGLE_PLAY_BUILD_NUMBER ]; then
              # fallback in case no build number was found from google play. Alternatively, you can `exit 1` to fail the build
              UPDATED_BUILD_NUMBER=$BUILD_NUMBER
          else
              UPDATED_BUILD_NUMBER=$(($LATEST_GOOGLE_PLAY_BUILD_NUMBER + 1))
          fi
          ./gradlew bundleRelease --stacktrace -PversionCode=$UPDATED_BUILD_NUMBER -PversionName=1.0.$UPDATED_BUILD_NUMBER
          
      - name: Set up key.properties
        script: | 
          cat >> "$CM_BUILD_DIR/key.properties" <<EOF
          storePassword=$CM_KEYSTORE_PASSWORD
          keyPassword=$CM_KEY_PASSWORD
          keyAlias=$CM_KEY_ALIAS
          storeFile=$CM_KEYSTORE_PATH
          EOF
          
      #- name: Wait for bundle file
      #  script: |
      #    # Define the path to the bundle file
      #    BUNDLE_FILE="${CM_BUILD_OUTPUT_DIR}/app-release.aab"
      # 
      #    # Wait for the bundle file to be created (poll every 10 seconds)
      #    while [ ! -f "$BUNDLE_FILE" ]; do
      #        echo "Waiting for bundle file to be created..."
      #        sleep 10
      #    done
          
      #- name: Set file permissions for app-release.aab
      #  script: |
      #    # Change the permissions for app-release.aab
      #    chmod 644 "${CM_BUILD_OUTPUT_DIR}/app-release.aab"
          
      - name: Signing the bundle
        script: |
          jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore "$CM_KEYSTORE_PATH" -storepass "$CM_KEYSTORE_PASSWORD" -keypass "$CM_KEY_PASSWORD" /Users/builder/clone/app/build/outputs/bundle/release/app-release.aab "$CM_KEY_ALIAS"
          
    artifacts:
      - app/build/outputs/**/*.aab
    publishing:
      email:
        recipients:
          - teacherjoseluis@gmail.com
        notify:
          success: true
          failure: false
      google_play:
        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        track: internal
        submit_as_draft: true
